name: Deploy website
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubutnu-latest
    steps:
      - name: checkout to repository
        uses: actions/checkout@v3
        
      - name: get all the output of data
        run: echo "${{ toJSON(github) }}"

     

      - name: Install dependencies
        run: npm ci
        
      - name: lint
        run: npm run lint
        
      - name: Test the code
        run: npm run test

  build:
    runs-on: ubutnu-latest
    steps:
      - name: checkout to repository
      - uses: actions/checkout@v3
  deploy:
    runs-on: ubutnu-latest
    steps:
      - name: build the code
        run: npm run build

      - name: deploy the code
        run: echo "deploying the code"
